"""Add index on user email

Revision ID: 28d417a7da92
Revises: 6bdd5a347513
Create Date: 2024-01-04 01:03:05.047821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28d417a7da92'
down_revision: Union[str, None] = '6bdd5a347513'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_auth_user_email'), 'auth_user', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auth_user_email'), table_name='auth_user')
    # ### end Alembic commands ###
