"""Make explanation optional

Revision ID: fa382656987f
Revises: f2c324004701
Create Date: 2023-12-28 11:21:27.571199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fa382656987f'
down_revision: Union[str, None] = 'f2c324004701'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions', 'explanation',
               existing_type=mysql.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions', 'explanation',
               existing_type=mysql.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
